"""add discord bot tables

Revision ID: 20251113120000
Revises:
Create Date: 2025-11-13 12:00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251113120000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_token', sa.String(length=255), nullable=False),
    sa.Column('guild_id', sa.String(length=128), nullable=True),
    sa.Column('guild_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('auto_sync_on_register', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_tag_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_config_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(length=128), nullable=False),
    sa.Column('role_name', sa.String(length=128), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discord_config_id'], ['discord_config.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_tag_mapping')
    op.drop_table('discord_config')
    # ### end Alembic commands ###